//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Parcial_Nomina.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomina
    {
        public int Id { get; set; }
        public Nullable<int> Ano { get; set; }
        public string Mes { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<double> Nomina1 { get; set; }

        
    }

    public enum Mes
    {
        Enero, Febrero, Marzo, Abril, Mayo, Junio, Julio, Agosto, Septiembre, Octubre, Noviembre, Diciembre
    }
}
